# Generated by Django 2.0.1 on 2018-02-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0002_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(default='www.google.com'),
        ),
    ]
