# Generated by Django 2.0.1 on 2018-03-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0007_auto_20180227_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='sa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=10000)),
            ],
        ),
    ]
