# Generated by Django 2.0.2 on 2018-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0008_sa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
